### ISSUE TITLE
[ documentation ] - Typo in button documentation: Incorrect Label for Icon Position

### ISSUE THREAD

**Issue by Jezda1337** [axzilla/goilerplate#4]
In the example of buttons with the icon on the left and right sides, both examples contain the same label.
![image](https://github.com/user-attachments/assets/8254e601-a20b-4868-b7b7-df4796030db6)

unfortunately there is no labels for the issue, so I put the label in the title.

**Comment by axzilla** [comment]
Hey thanks buddy. I just fixed it!
